---
- hosts: localhost
  become: yes
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www
    app_root: /root/html_demo_site-main 
  tasks:
    - name: Install nginx via amazon linux
      command: 'amazon-linux-extras install nginx1'

    - name: Copy website files to the server's document root
      copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        mode: preserve

    - name: Apply Nginx template
      copy:
        src: files/nginx.conf.j2
        dest: /etc/nginx/sites-available/default/nginx.conf
        mode: preserve

    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default/nginx.conf
        dest: /etc/nginx/sites-enabled/default/nginx.conf
        state: link
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        command: 'systemctl restart nginx'
        state: restarted